# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "Zocoi"
tagline:             "Vietnamese /ʒoʊ kɔɪ/: (informal) Let's watch/read together"
description:         "Hưng Đào's thoughts on life and tech" # 'Hưng Đào homepage and blog about tech, side projects, thoughts and life updates'
url:                 https://zocoi.com
baseurl:             ''
paginate:            10

include             : ["_pages"]

# About/contact
author:
  name:              Hung Dao
  url:               https://zocoi.com/about
  email:             

# Custom vars
version:             1.0.0
